apiVersion: mcp.mcp-operator.io/v1
kind: MCPServer
metadata:
  name: mcp-everything-server
  namespace: mcp-tests
  labels:
    app.kubernetes.io/name: mcp-operator
    app.kubernetes.io/managed-by: kustomize
    mcp.example: mcp-everything-server
spec:
  image: "tzolov/mcp-everything-server:v3"

  command: ["node", "dist/index.js", "sse"]

  transport:
    type: "http"
    config:
      http:
        port: 8080
        path: "/mcp"
        sessionManagement: true
