apiVersion: mcp.mcp-operator.io/v1
kind: MCPServer
metadata:
  labels:
    app.kubernetes.io/name: mcp-operator
    app.kubernetes.io/managed-by: kustomize
  name: mcpserver-sample
spec:
  # TODO(user): Add fields here
